name: Make Compilation Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
    
    - name: check c++ version
      run: c++ --version

    - name: Find and test all Makefiles
      run: |
        # Find all directories containing Makefiles
        find . -name "Makefile" -type f -print0 | while IFS= read -r -d '' makefile; do
          echo "Testing Makefile in $(dirname "$makefile")"
          
          # Navigate to the Makefile's directory
          cd "$(dirname "$makefile")" || exit 1
          
          # Run make
          if ! make; then
            echo "::error::Make failed in $(dirname "$makefile")"
            exit 1
          fi
          
          # Clean after successful build
          make clean || true
          
          # Return to the root directory
          cd "$GITHUB_WORKSPACE" || exit 1
        done
